export const data = [
  {
    holder: "Makuza Mugabo",
    cardno: "RCA0114MHB",
    balance: "20000RWF",
    year: "Year 1",
    class: "class B",
  },
  {
    holder: "Makuza Mugabo",
    cardno: "RCA0114MHB",
    balance: "20000RWF",
    year: "Year 1",
    class: "class B",
  },
  {
    holder: "Makuza Mugabo",
    cardno: "RCA0114MHB",
    balance: "20000RWF",
    year: "Year 1",
    class: "class B",
  },
  {
    holder: "Makuza Mugabo",
    cardno: "RCA0114MHB",
    balance: "20000RWF",
    year: "Year 1",
    class: "class B",
  },
  {
    holder: "Makuza Mugabo",
    cardno: "RCA0114MHB",
    balance: "20000RWF",
    year: "Year 1",
    class: "class B",
  },
  {
    holder: "Makuza Mugabo",
    cardno: "RCA0114MHB",
    balance: "20000RWF",
    year: "Year 1",
    class: "class B",
  },
  {
    holder: "Makuza Mugabo",
    cardno: "RCA0114MHB",
    balance: "20000RWF",
    year: "Year 1",
    class: "class B",
  },
  {
    holder: "Makuza Mugabo",
    cardno: "RCA0114MHB",
    balance: "20000RWF",
    year: "Year 1",
    class: "class B",
  },
  {
    holder: "Makuza Mugabo",
    cardno: "RCA0114MHB",
    balance: "20000RWF",
    year: "Year 1",
    class: "class B",
  },
  {
    holder: "Makuza Mugabo",
    cardno: "RCA0114MHB",
    balance: "20000RWF",
    year: "Year 1",
    class: "class B",
  },
];
